config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :cocktails, only: [:index, :show, :new, :create] do
  resources :doses, only: [:new, :create]
  end
delete '/doses/:id', to: 'doses#destroy', as: 'dose'
root 'cocktails#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cocktail.rb
class Cocktail < ApplicationRecord
  validates :name, presence: true, uniqueness: true
  has_many :doses, dependent: :destroy
  has_many :ingredients, through: :doses
  has_one_attached :photo
end

app/models/dose.rb
class Dose < ApplicationRecord
  belongs_to :cocktail
  belongs_to :ingredient
  validates :description, presence: true
  validates :cocktail_id, uniqueness: { scope: :ingredient_id }
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  has_many :doses
  validates :name, presence: true, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/cocktails_controller.rb
class CocktailsController < ApplicationController
  def index
    @cocktails = Cocktail.all
  end

  def show
    @cocktail = Cocktail.find(params[:id])
    @dose = Dose.new
  end

  def new
    @cocktail = Cocktail.new
  end

  def create
    @cocktail = Cocktail.new(cocktail_params)
    if @cocktail.save
      redirect_to cocktail_path(@cocktail)
    else
      render :new
    end
  end

  private

  def cocktail_params
    params.require(:cocktail).permit(:name, :photo)
  end
end

app/controllers/doses_controller.rb
class DosesController < ApplicationController
   def new
    @dose = Dose.new
    @cocktail = Cocktail.find(params[:cocktail_id])
   end

  def create
    @cocktail = Cocktail.find(params[:cocktail_id])
    @dose = Dose.new(dose_params)
    @dose.cocktail = @cocktail
    if @dose.save
      redirect_to cocktail_path(@cocktail)
    else
      render :new
    end
  end

  def destroy
    @dose = Dose.find(params[:id])
    @cocktail = @dose.cocktail
    @dose.destroy
    redirect_to cocktail_path(@cocktail)
  end

  private

  def dose_params
    params.require(:dose).permit(:description, :ingredient_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cocktails_helper.rb
module CocktailsHelper
end

app/helpers/doses_helper.rb
module DosesHelper
end

app/views/cocktails/index.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <%= link_to "#", class: "navbar-brand" do %>
    <%= image_tag "https://www.seekpng.com/png/detail/25-254033_cocktail-glass-drawing-png.png" %>
  <% end %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <%= link_to "Home", cocktails_path, class: "nav-link" %>
      </li>
      <%= link_to "Add your drink", new_cocktail_path, class: "btn btn-primary pad20" %>
    </ul>
  </div>
</div>
<div class="container">
  <!-- Heading -->
  <h1 class="mt-4">Goldene Bar</h1>
    <!-- Grid row -->
  <div class="row">
    <!-- Card -->
    <% @cocktails.each do |cocktail| %>
      <div class="card m-4">
        <img class="card-img-top" src="<%= cl_image_path cocktail.photo.key, height: 300, width: 400, crop: :fill %>" alt="Card image top">
        <div class="card-body">
          <h3 class="card-title"><%= cocktail.name %></h3>
          <%= link_to "See recipe", cocktail_path(cocktail), class: "card-link" %>
        </div>
      </div>
    <% end %>
  </div>
<!-- Close main div -->
</div>

app/views/cocktails/new.html.erb
<div class="container padded">
  <h1 class="text-center">Add new cocktail</h1>
  <div class="row">
    <div class="col-xs-12 col-md-6 col-md-offset-3">
        <%= simple_form_for @cocktail do |f| %>
          <%= f.input :name %>
          <%= f.input :photo, as: :file %>
          <%= f.submit "Submit", class: "btn btn-primary" %>
        <% end %>
          <%= link_to "Go back", cocktails_path, class: "card-link" %>
    </div>
  </div>
</div>

app/views/cocktails/show.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <%= link_to "#", class: "navbar-brand" do %>
    <%= image_tag "https://www.seekpng.com/png/detail/25-254033_cocktail-glass-drawing-png.png" %>
  <% end %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <%= link_to "Home", cocktails_path, class: "nav-link" %>
      </li>
      <%= link_to "Add your cocktail", new_cocktail_path, class: "btn btn-primary pad20" %>
    </ul>
  </div>
</div>
<div class="container">
  <!-- Heading -->
  <h1 class="mt-4"> <%= @cocktail.name %> </h1>
    <%= cl_image_tag @cocktail.photo.key, height: 400, width: 300, crop: :fill %>
  <!-- Ingredient heading -->
  <div class="mt-4">
    <% if @cocktail.doses.empty? %>
    <p class="text-gray">
      No ingredients yet. Add yours!
    </p>
    <% else %>
    <h3> Ingredients </h2>
      <% end %>
  </div>
  <!-- Ingredient list -->
  <ul class="list-unstyled">
    <% @cocktail.doses.each do |d| %>
    <li>
      <i><%= d.ingredient.name %> | <%= d.description %></i>
      <%= link_to "Delete", dose_path(d), class: "btn btn-danger btn-xs", method: :delete  %>
    </li>
    <p><%= d.description %></p>
    <% end %>
  </ul>
  <div>
    <%= link_to "Add ingredient", new_cocktail_dose_path(@cocktail), class: "btn btn-primary", id: "ingredient-add-button"%>
    <%= link_to "Go back", cocktails_path, class: "card-link" %>
  </div>
</div>

app/views/doses/new.html.erb
<div class="container">
  <h3 class="text-center">Add an ingredient</h1>
  <div class="row">
    <div>
      <%= simple_form_for [@cocktail, @dose] do |f| %>
      <%= f.association :ingredient%>
      <%= f.input :description %>
      <%= f.submit "Submit", class: "btn btn-primary" %>
      <% end %>
      <div>
        <%= link_to "Go back", cocktails_path, class: "card-link" %>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsMisterCocktail</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
  </head>

  <body>
    <%= yield %>
  </body>
</html>